name: Step-time Biofeedback Project

on:
  push:
    branches:  
      - feature/*
  pull_request:
    branches:  
      - feature/*
  workflow_dispatch:
    
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Download the virtual environment
        run: pip install virtualenv

      - name: Create the virtual environment
        run: virtualenv env

      - name: Activate the virtual environment
        run: source env/bin/activate

      - name: Move to base of repository
        run: cd ${{github.workspace}}

      - name: Download the project requirements
        run: pip install -r requirements.txt

      - name: Install frontend dependencies
        run: |
          cd ${{ github.workspace }}/frontend
          npm install

      - name: Run the frontend tests
        run: npm test

      - name: Shutdown the virtual environment
        run: deactivate
